- .github/workflows/main.yml
- src/main/java/com/example/vcloset/logic/entity/user/User.java
- src/test/java/com/example/vcloset/logic/rest/UserRestControllerTest.java
Se agrega entidad Usuarios con sus atributos, y JUnit del UserRestController
> Se agrega entidad Usuarios con sus atributos, y JUnit del UserRestController

- src/main/java/com/example/vcloset/logic/entity/user/User.java
Se agregan atributos al User para inactividad y privacidad del perfil
> Se agregan atributos para el usuario de privacidad y activo

- src/test/java/com/example/vcloset/logic/rest/auth/AuthRestControllerTest.java
Se agrega JUnit del BE auth SignUp test
> Se agrega JUnit del BE auth SignUp test

- src/main/java/com/example/vcloset/logic/entity/user/User.java
Se agrega default en la variable isUserActive
> Se agrega default en la variable isUserActive

- src/main/java/com/example/vcloset/rest/clothing/ClothingRestController.java
agrega requests que fueron sobre escritos por PR anterior.
> technest-DEV: resuelve overwrite del ClothingRestController

- src/main/java/com/example/vcloset/rest/user/UserRestController.java
incluye patch method para actualizar la imagen del perfil de usuario
> technest-5: incluye http patch para foto de perfil

- src/main/java/com/example/vcloset/rest/auth/AuthRestController.java
- src/main/java/com/example/vcloset/rest/user/UserRestController.java
- El borrado es lógico, por lo que se cambia el estado isUserActive, y se redirige al usuario al login, se incluye la lógica para que no permita la autenticación de usuarios "eliminados".
- Se incluye el patch request para cambiar la contraseña junto con su encoding respectivo.
> Technest 5/rf09 actualizar perfil usuario

- src/main/java/com/example/vcloset/logic/entity/clothing/ClothingRepository.java
- src/main/java/com/example/vcloset/rest/clothing/ClothingRestController.java
- src/main/resources/sql/procedures.sql
Endpoints y procedimiento almacenado para el get de prendas por tipo. Todos los filtros funcionales.
> Technest 56/listado prendas

- src/main/java/com/example/vcloset/logic/entity/clothing/ClothingRepository.java
- src/main/java/com/example/vcloset/rest/clothing/ClothingRestController.java
- src/main/resources/sql/procedures.sql
Reverts TechNest-CENFO/vcloset-backend#22
> Revert "Revert "Technest 56/listado prendas""

- src/main/java/com/example/vcloset/logic/entity/clothing/Clothing.java
- src/main/java/com/example/vcloset/logic/entity/outfit/Outfit.java
- src/main/java/com/example/vcloset/rest/outfit/OutfitRestController.java
Cambios en los json ignore de outfit y clothing, post de outfit manules y cambio en el fetch y cascade del set de clothing en outfit
> Technest 21/rf14 creacion de outfits manuales

- src/main/java/com/example/vcloset/rest/outfit/OutfitRestController.java
Logica de guardado y ajustes en la lista de outfits random
> Logica de guardado y ajustes en la lista de outfits random

- src/main/java/com/example/vcloset/rest/outfit/OutfitRestController.java
- src/main/resources/sql/procedures.sql
Se mejora la lógica para retornar un clothing
> Se mejora la lógica para retornar un clothing

- src/main/java/com/example/vcloset/rest/outfit/OutfitRestController.java
Reverts TechNest-CENFO/vcloset-backend#35
> Revert "Logica para vestidos"

- src/main/java/com/example/vcloset/rest/outfit/OutfitRestController.java
Reverts TechNest-CENFO/vcloset-backend#36
> Revert "Revert "Logica para vestidos""

- src/main/java/com/example/vcloset/logic/entity/outfit/Outfit.java
- src/main/java/com/example/vcloset/logic/entity/outfit/OutfitRepository.java
- src/main/java/com/example/vcloset/rest/outfit/OutfitRestController.java
>  Eliminacion de outfits 

- src/main/java/com/example/vcloset/logic/entity/outfit/Outfit.java
- src/main/java/com/example/vcloset/rest/clothing/ClothingRestController.java
- src/main/java/com/example/vcloset/rest/outfit/OutfitRestController.java
Endpoints de favoritos & isPublic
> Technest 33/rf 17 rf 21

- src/main/java/com/example/vcloset/rest/outfit/OutfitRestController.java
Tecnest 24 25/rf 15 16 eliminacion y edicion de outfits
> Tecnest 24 25/rf 15 16 eliminacion y edicion de outfits

- src/main/java/com/example/vcloset/logic/entity/weather/WeatherApiResponse.java
- src/main/java/com/example/vcloset/logic/entity/weather/WeatherData.java
- src/main/java/com/example/vcloset/logic/service/weather/WeatherService.java
- src/main/java/com/example/vcloset/rest/weather/WeatherRestController.java
- src/main/resources/sql/procedures.sql
> Se agrega api del clima

- src/main/java/com/example/vcloset/logic/service/outfit/OutfitService.java
- src/main/java/com/example/vcloset/rest/outfit/OutfitRestController.java
- src/main/java/com/example/vcloset/rest/recommendations/RecommendationsRestController.java
- src/main/resources/sql/procedures.sql
Se agrega logica para outfit semanales
> Se agrega logica para outfit semanales

- src/main/java/com/example/vcloset/logic/entity/clothing/Clothing.java
- src/main/resources/sql/procedures.sql
agrega JsonIgnore requerido en clothing y elimina SP no utilizado
> Technest 42/rf27 modulo prestamos
